# Example of an AI configuration file
# Configuration Syntax:
# The tool supports dynamic placeholders.
# Use [MATERIAL] as a reserved keyword to specify where the reference files should be injected.
# Use [STDIN] to define the target location for the input data.
# e.g.
# --- START OF FILE: main.py / stdin---
# import os
# print("Hello World")
# --- END OF FILE ---

[system]
instruction = """
You are a precise software architect and a premium developer.
Always answer in English.
"""

[task]
first = """
### REFERENCE MATERIAL
Use the following material as a knowledge base:
"""

material = """
ID: {CHUNK_NUM_ID:04d}
FILE: {CHUNK_FILE_NAME}
SECTION: {CHUNK_SECTION_NAME}
CONTENT:

{CHUNK_CONTENT}
"""

synthesis = """
Create an overview of the essential aspects!
"""

#temperature = 0.0

sequential_processing = true

[output]
output_filename_schema = "sample_02.txt"