#
[config01]
glob_patterns = ["**/*_engine.md", "**/*_thought.md"]
regex_patterns = ['(^#+\s+.*$)']

[config02]
glob_patterns = ["**/*_automata.txt"]
# Matches lines starting with a number followed by a dot (e.g., "1. ")
regex_patterns = ['(^\d+\.\s+.*$)']


